version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/react-testing-talk
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Testing
          command: yarn test -- --coverage
      - run:
          name: Submitting code coverage to codecov
          command: curl -s https://codecov.io/bash | bash
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  node-8:
    <<: *test
    docker:
      - image: node:8

workflows:
  version: 2
  build_and_test:
    jobs:
      - node-latest
      - node-8
